name: Docker Image CI

on:
  push:
    branches:
      - 'master'

# Refer to: https://github.com/docker/build-push-action && https://github.com/docker/metadata-action
jobs:
  build-multiple-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USER }}/godaddy-ddns
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix={{date 'YYYYMMDD'}}-,format=short
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=alpine,enable={{is_default_branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: |
            linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=alpine
          platforms: |
            linux/amd64,linux/arm64